parameters:
    mailer_user: "test@email.com"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Seraph\Bundle\MediaBundle\Entity\User
    group:
        group_class: Seraph\Bundle\MediaBundle\Entity\Group
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"