parameters:
    app.path.uploaded_file: /uploads/

vich_uploader:
    db_driver: orm

    mappings:
        uploaded_file:
            uri_prefix: '%app.path.uploaded_file%'
            upload_destination: '%kernel.root_dir%/../web/uploads/'