services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Seraph\Bundle\MediaBundle:
        resource: '../../*'
        exclude: '../../{Controller, Entity, Form, Resources, Twig}'

    Seraph\Bundle\MediaBundle\Controller:
        resource: '../../Controller'
        tags : ['controller.service_arguments']