services:
    Seraph\Bundle\MediaBundle\Twig\:
            resource: '../../Twig'
            tags: ['twig.extension']
            arguments:
                $registry: '@doctrine'
                $twig: '@twig'