parameters:
    app.path.uploaded_file: '%seraph_upload_folder%'

vich_uploader:
    db_driver: orm

    mappings:
        uploaded_file:
            uri_prefix: '%app.path.uploaded_file%'
            upload_destination: '%kernel.root_dir%/../web/%seraph_upload_folder%/'